plugins {
    id 'com.android.library'
    id 'org.jetbrains.kotlin.android'
    id 'maven-publish'
    id("com.vanniktech.maven.publish") version "0.35.0"
}

android {
    compileSdk 35

    defaultConfig {
        minSdk 26
        targetSdk 35

        vectorDrawables.useSupportLibrary = true
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
    buildFeatures {
        buildConfig true
    }
    lintOptions {
        abortOnError false
    }
    namespace "com.luck.picture.lib"
    kotlinOptions {
        jvmTarget = '17'
    }
}

dependencies {
    implementation "androidx.appcompat:appcompat:${cfgs.version_appcompat}"
    implementation "androidx.recyclerview:recyclerview:${cfgs.version_recyclerview}"
    implementation "androidx.activity:activity:${cfgs.activity_version}"
    implementation "androidx.fragment:fragment:${cfgs.fragment_version}"
    implementation "androidx.exifinterface:exifinterface:${cfgs.exifinterface_version}"
    implementation "androidx.viewpager2:viewpager2:${cfgs.viewpage2}"
    implementation "androidx.constraintlayout:constraintlayout:${cfgs.constraintlayout}"
    implementation 'androidx.core:core-ktx:1.13.1'
    implementation 'androidx.activity:activity-ktx:1.10.1'
}

mavenPublishing {
    publishToMavenCentral()
    signAllPublications()
}

mavenPublishing {
    coordinates("io.github.jzlhll", "pictureselector", "3.16.6")

    pom {
        name = "pictureselector"
        description = "This is my android project picture selector."
        inceptionYear = "2026"
        url = "https://github.com/jzlhll/PictureSelector"
        licenses {
            license {
                name = "The Apache License, Version 2.0"
                url = "http://www.apache.org/licenses/LICENSE-2.0.txt"
                distribution = "http://www.apache.org/licenses/LICENSE-2.0.txt"
            }
        }
        developers {
            developer {
                id = "jzlhll"
                name = "jzlhll"
                url = "https://github.com/jzlhll/"
            }
        }
        scm {
            url = "https://github.com/jzlhll/PictureSelector"
            connection = "scm:git:git://github.com/jzlhll/PictureSelector.git"
            developerConnection = "scm:git:ssh://git@github.com/jzlhll/PictureSelector.git"
        }
    }
}
